# Generated by Django 6.0.7 on 2026-08-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(db_index=True, max_length=50)),
                ('year', models.IntegerField(db_index=True)),
                ('period', models.CharField(db_index=True, max_length=10)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('tmin', models.FloatField(blank=True, null=True)),
                ('tmean', models.FloatField(blank=True, null=True)),
                ('sun', models.FloatField(blank=True, null=True)),
                ('rain', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
                'indexes': [models.Index(fields=['region', 'year'], name='weather_wea_region_152d51_idx')],
                'unique_together': {('region', 'year', 'period')},
            },
        ),
    ]
