# Generated by Django 6.0.7 on 2026-08-01 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('period_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WINTER', 'Winter'), ('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.parameter')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='weather.region')),
            ],
            options={
                'ordering': ['-year', 'month'],
                'indexes': [models.Index(fields=['region', 'parameter', 'year'], name='weather_wea_region__be897c_idx')],
                'unique_together': {('region', 'parameter', 'year', 'month', 'period_type')},
            },
        ),
    ]
